### ISSUE TITLE
Not able to share image on Twitter.

### ISSUE THREAD

**Issue by ucpritam** [bedirhanssaglam/social_sharing_plus#1]

**Comment by ucpritam** [comment]
I am not able to share image on Twitter on iOS.

**Comment by bedirhanssaglam** [comment]
> I am not able to share image on Twitter on iOS.

`/// * [image]: The image to be shared. (Android only)`

Hi @ucpritam!  As stated in the relevant method and comment line, the image sharing feature is not yet stable on the iOS platform. I'm working on this. Thank you for your interest!
