### ISSUE TITLE
Facebook home page open, nor the page for share in feed

### ISSUE THREAD

**Issue by LiramVahady** [bedirhanssaglam/social_sharing_plus#13]
The idea when select facebook move to facebook free text create post page is only open the facebook app :(

**Comment by bedirhanssaglam** [comment]
Hi @LiramVahady 

Thanks for the issue(!). You provided incomplete information, therefore your issue will be closed. Please provide more details about your problem so I can help.

**Comment by svarup** [comment]
Same issue, This will only open the facebook app home page and does not open the facebook share page

```
await SocialSharingPlus.shareToSocialMedia(
    SocialPlatform.facebook,
    url,
    isOpenBrowser: true,
);
```
