### ISSUE TITLE
Not able to share file+text together on whatsapp

### ISSUE THREAD

**Issue by ArisChoice** [bedirhanssaglam/social_sharing_plus#8]
await SocialSharingPlus.shareToSocialMedia(
    SocialPlatform.whatsapp,
    'Msg text',
    media: file.path,
    isOpenBrowser: false,
  );

**ERROR**
 Unhandled Exception: Exception: Failed to share to SocialPlatform.whatsapp: Couldn't find meta-data for provider with authority com.ks.dev.fileprovider

**Comment by bedirhanssaglam** [comment]
Hi @ArisChoice 
Thank you for issue.

What type of file do you want to share, and have you completed the setup mentioned at https://pub.dev/packages/social_sharing_plus#setup? If so, could you share it?
